:schedule:
  hello_world:
    cron: "0 * 6 * * *"
    class: HelloWorldWorker
  collection_artlce:
    cron: "0 */30 * * * *"
    class: CollectArticleWorker
  create_user_recommended:
    cron: "0 55 6,11,18 * * *"
    class: CreateUserRecommended
